server:
  http:
    port: 8080
    host: ""
    production: true
service:
  scheduler:
    enabled: false
    interval: "3s"



datasource:
observability:
  tracing:
    enabled: false
    zipkin:
      url: "http://localhost:9411/api/v2/spans"
      service_name: "greeter"
  metrics:
    enabled: false
    prometheus:
      port: 9090
      host: "localhost"
      path: "/metrics"
  logging:
    level: "info"
    logstash:
      enabled: false
      address: "127.0.0.1:9000"

