// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/config"
	http2 "application/internal/v1/http"
	"application/internal/v1/http/handler"
	"context"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

func wireApp(ctx context.Context, cfg config.Config, logger *slog.Logger) (http.Handler, error) {
	v := handler.NewServiceList()
	httpHandler := http2.NewHTTPHandler(v...)
	return httpHandler, nil
}
