basePath: /v2
definitions:
  application_internal_http_dto.SampleEntityRequest:
    properties:
      name:
        type: string
      text:
        type: string
    required:
    - name
    - text
    type: object
  application_internal_http_dto.SampleEntityResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      text:
        type: string
    type: object
  application_internal_http_response.Response-application_internal_http_dto_SampleEntityResponse:
    properties:
      data:
        $ref: '#/definitions/application_internal_http_dto.SampleEntityResponse'
      message:
        type: string
      status:
        type: integer
    type: object
  application_internal_http_response.Response-application_internal_http_swagger_EmptyObject:
    properties:
      data:
        $ref: '#/definitions/application_internal_http_swagger.EmptyObject'
      message:
        type: string
      status:
        type: integer
    type: object
  application_internal_http_response.Response-array_application_internal_http_dto_SampleEntityResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/application_internal_http_dto.SampleEntityResponse'
        type: array
      message:
        type: string
      status:
        type: integer
    type: object
  application_internal_http_swagger.EmptyObject:
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /sample-entities:
    get:
      consumes:
      - application/json
      description: Get all sample entities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-array_application_internal_http_dto_SampleEntityResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
      summary: Get all sample entities
      tags:
      - SampleEntity
    post:
      consumes:
      - application/json
      description: Create Sample Entity
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/application_internal_http_dto.SampleEntityRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_dto_SampleEntityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
      summary: Create Sample Entity
      tags:
      - SampleEntity
  /sample-entities/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Sample Entity
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
      summary: Delete Sample Entity
      tags:
      - SampleEntity
    put:
      consumes:
      - application/json
      description: Update Sample Entity
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/application_internal_http_dto.SampleEntityRequest'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/application_internal_http_response.Response-application_internal_http_swagger_EmptyObject'
      summary: Update Sample Entity
      tags:
      - SampleEntity
swagger: "2.0"
